install_centos:
	make -C centos/ install

install_debian:
	make -C debian/ install

install_deepin:
	make -C deepin/ install

install_fedora:
	make -C fedora/ install

install_redhat:
	make -C redhat/ install

install_ubuntu:
	make -C ubuntu/ install

install_freebsd:
	cd freebsd && make install && cd ..

