#!/bin/sh

if [ `id -u` -ne 0 ]; then
	echo "Current user is not root."
	exit 1
fi

./deps

if [ $? -ne 0 ]; then
	echo "Failed to build dependencies."
	exit 1
fi

./do

if [ $? -ne 0 ]; then
	echo "Failed to build uSched."
	exit 1
fi

./install

if [ $? -ne 0 ]; then
	echo "Failed to install uSched."
	exit 1
fi

./undo

if [ $? -ne 0 ]; then
	echo "uSched was deployed but it failed to cleanup."
	exit 1
fi

echo "uSched was successfully deployed."

exit 0

