#!/bin/sh

install_lib()
{
	lib=${1}
	cd ${lib}

	if [ -e `which wget` ]; then
		wget https://github.com/ucodev/${lib}/archive/master.tar.gz
	elif [ -e `which curl` ]; then
		curl -O https://github.com/ucodev/${lib}/archive/master.tar.gz
	else
		echo "Can't find 'wget' nor 'curl'."
		exit 1
	fi

	tar zxvf master.tar.gz
	cd ${lib}-master

	if [ -e "target" ]; then
		if [ -e "../../../.target" ]; then
			./target `cat ../../../.target`
		fi
	fi

	./do && ./install

	if [ ${?} -ne 0 ]; then
		echo "Unable to install ${lib}"
		exit 1;
	fi

	cd ../../
}

# Check if we're root
if [ `id -u` -ne 0 ]; then
	echo "Current user is not root"
	exit 1
fi

# Check if tar is installed
if ! [ -e "`which tar`" ]; then
	echo "tar isn't installed"
	exit 1
fi

# Check if gunzip is installed
if ! [ -e "`which gunzip`" ]; then
	echo "gunzip isn't installed"
	exit 1
fi

# Check if unzip is installed
if ! [ -e "`which wget`" ]; then
	echo "wget isn't installed"
	exit 1
fi

# Prepare
echo "Installing dependencies..."
rm -rf build
mkdir build
mkdir build/libfsma
mkdir build/libfsop
mkdir build/libpall
mkdir build/libpanet
mkdir build/libpsched
mkdir build/libpsec
mkdir build/librtsaio
cd build

# Install dependencies
install_lib "libfsma"
install_lib "libfsop"
install_lib "libpall"
install_lib "libpanet"
install_lib "libpsched"
install_lib "libpsec"
install_lib "librtsaio"

# Cleanup
cd ../
rm -rf build

# Exit
echo "Dependencies installed."

exit 0

