#!/bin/sh

if ! [ -e ".done" ]; then
	echo "Run 'do' first"
	exit 1
fi

if [ `id -u` -ne 0 ]; then
	echo "Current user is not root"
	exit 1
fi

make install_all

if [ $? -ne 0 ]; then
	echo "Installation failed."
	exit 1;
fi

make install_doc

if [ $? -ne 0 ]; then
	echo "The installation of the documentation has failed."
	exit 1;
fi

if [ ! -z `which ldconfig` ]; then
	ldconfig

	if [ $? -ne 0 ]; then
		echo "Failed to execute ldconfig"
		exit 1;
	fi
fi

echo "Installation complete."

exit 0

