#!/bin/sh

if [ $# -ne 1 ]; then
	echo "Usage: ${0} <special target>"
	echo ""
	echo "Special targets: rpi, bbb"
	echo ""
	echo "\trpi - Raspberry PI"
	echo "\tbbb - Beaglebone Black"
	echo ""
	exit 1
fi

if [ ${1} = "rpi" ]; then
	echo "Selected target is: Raspberry PI"
elif [ ${1} = "bbb" ]; then
	echo "Selected target is: Beaglebone Black"
else
	echo "Unknown target."
	exit 1
fi

printf -- ${1} > .target

