#!/bin/sh
# uCodev uSched
# uSched init script

#
# Date: 18-02-2015
# 
# Copyright 2014-2015 Pedro A. Hortas (pah@ucodev.org)
#
# This file is part of usched.
#
# usched is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# usched is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with usched.  If not, see <http://www.gnu.org/licenses/>.
#

# PROVIDE: usched
# KEYWORD: nojail

. /etc/rc.subr
                
name="usched"
rcvar="usched_enable"
command="/usr/sbin/${name}"
start_cmd="start"
stop_cmd="stop"


flush()
{
	echo -n "Flushing uSched services... "

	/usr/sbin/usched flush quiet

	if [ $? -ne 0 ]; then
		echo -n "Unable to flush services. "
		echo "Failed"
		return 1
	fi

	echo "OK"
}

reload()
{
	echo -n "Reloading uSched services... "

	/usr/sbin/usched reload quiet

	if [ $? -ne 0 ]; then
		echo -n "Unable to reload services. "
		echo "Failed"
		return 1
	fi

	echo "OK"
}

start()
{
	echo -n "Starting uSched services... "

	/usr/sbin/usched start quiet

	if [ $? -ne 0 ]; then
		echo -n "Unable to start services. "
		echo "Failed"
		return 1
	fi


	echo "OK"
}

stop()
{
	echo -n "Stopping uSched services... "
	
	/usr/sbin/usched stop quiet

	if [ $? -ne 0 ]; then
		echo -n "Unable to stop services. "
		echo "Failed"
		return 1
	fi

	echo "OK"
}

status()
{
	echo -n "Checking uSched services status... "

	if [ ! -f /var/run/usched_usd.pid ]; then
		echo -n "uSched Daemon Service isn't running. "
		echo "Failed"
		return 1
	fi

	if [ ! -f /var/run/usched_use.pid ]; then
		echo -n "uSched Exec Service isn't running. "
		echo "Failed"
		return 1
	fi

	echo "OK"
}

case "$1" in
flush)
	flush
	;;
start)
	start
	;;
stop)
	stop
	;;
reload)
	reload
	;;
restart)
	stop && start
	;;
status)
	status
	;;
*)
	echo "Usage: $0 {flush|status|start|stop|reload|restart}"
	exit 1
esac

