pdf_ref:
	cd lyx && make pdf && cd ..

html_ref:
	cd lyx && make html && cd ..

man:
	cd man && make && cd ..

man_install:
	cd man && make install && cd ..

text_install:
	cd text && make install && cd ..

