pdf_ref:
	cd lyx && make pdf && cd ..

html_ref:
	cd lyx && make html && cd ..

manpages:
	cd man && make && cd ..

manpages_install:
	cd man && make install && cd ..

text_install:
	cd text && make install && cd ..

doxygen_files:
	cd doxygen && make && cd ..

clean:
	cd doxygen && make clean && cd ..
	cd lyx && make clean && cd ..
	cd man && make clean && cd ..

