all:

install:
	make -C mgmt/ install

install_centos:
	make -C init/ install_centos

install_debian:
	make -C init/ install_debian

install_deepin:
	make -C init/ install_deepin

install_fedora:
	make -C init/ install_fedora

install_redhat:
	make -C init/ install_redhat

install_ubuntu:
	make -C init/ install_ubuntu

clean:

