all:

install:
	make -C mgmt/ install

install_classic_centos:
	make -C init/ install_centos

install_classic_debian:
	make -C init/ install_debian

install_classic_deepin:
	make -C init/ install_deepin

install_classic_fedora:
	make -C init/ install_fedora

install_classic_redhat:
	make -C init/ install_redhat

install_classic_ubuntu:
	make -C init/ install_ubuntu

install_systemd:
	make -C systemd/ install

clean:

