all:

install:
	cd mgmt && make install && cd ..

install_classic_centos:
	cd init && make install_centos && cd ..

install_classic_debian:
	cd init && make install_debian && cd ..

install_classic_deepin:
	cd init && make install_deepin && cd ..

install_classic_fedora:
	cd init && make install_fedora && cd ..

install_classic_redhat:
	cd init && make install_redhat && cd ..

install_classic_ubuntu:
	cd init && make install_ubuntu && cd ..

install_freebsd:
	cd init && make install_freebsd && cd ..

install_systemd:
	cd systemd && make install && cd ..

clean:

