all:

install_all:
	cd csharp && make && make install && cd ..
	cd java && make && make install && cd ..
	cd php && make && make install && cd ..
	cd python && make && make install && cd ..

install_csharp:
	cd csharp && make && make install && cd ..

install_java:
	cd java && make && make install && cd ..

install_php:
	cd php && make && make install && cd ..

install_python:
	cd python && make && make install && cd ..

clean:
	cd csharp && make clean && cd ..
	cd java && make clean && cd ..
	cd php && make clean && cd ..
	cd python && make clean && cd ..

