all:
	cd common && make && cd ..
	cd usa && make && cd ..
	cd usc && make && cd ..
	cd usd && make && cd ..
	cd use && make && cd ..
	cd usm && make && cd ..
	cd uss && make && cd ..

install:
	cd usa && make install && cd ..
	cd usc && make install && cd ..
	cd usd && make install && cd ..
	cd use && make install && cd ..
	cd usm && make install && cd ..
	cd uss && make install && cd ..

clean:
	cd common && make clean && cd ..
	cd usa && make clean && cd ..
	cd usc && make clean && cd ..
	cd usd && make clean && cd ..
	cd use && make clean && cd ..
	cd usm && make clean && cd ..
	cd uss && make clean && cd ..

