.\" This file is part of the uCodev uSched project (http://www.usched.org)
.TH USM "1" "March 2015" "uCodev uSched v0.1" "User Commands"
.SH NAME
usm \- uSched Monitor
.SH SYNOPSIS
.B usm ...
.SH DESCRIPTION
.PP
The uSched Monitor. This command shall not be directly invoked by any user. See \fBusched\fR(1).
.PP
.SH AUTHOR
Written by Pedro A. Hortas (pah@ucodev.org).
.SH "REPORTING BUGS"
Report uSched bugs to \fIbugs@usched.org\fR
.PP
uSched home page: <http://www.usched.org>
.PP
.SH COPYRIGHT
Copyright \(co 2014-2015  Pedro A. Hortas (pah@ucodev.org)
.br
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.br
.PP
This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.PP
.SH "SEE ALSO"
\fBusched\fR(1), \fBusa\fR(1), \fBusc\fR(1), \fBusd\fR(1), \fBuse\fR(1)
.PP
The full documentation for
.B uSched
is available at:
.PP
.PP
  \fIhttp://www.usched.org/doc/uSched_Reference_Manual.html\fR
.PP
